// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sjsjvrpqxzmmebtojizf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNqc2p2cnBxeHptbWVidG9qaXpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MzY1NTEsImV4cCI6MjA2OTExMjU1MX0.qNn1ZwdCn2PqGzXOuCH0-yxWTgjAn3RDdtCLtQBFkCQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});